# Generated by Django 6.0 on 2025-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, choices=[('Inner Kathmandu', 'Inner Kathmandu'), ('Outer Kathmandu', 'Outer Kathmandu')], max_length=20, null=True),
        ),
    ]
