# Generated by Django 6.0 on 2026-01-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(choices=[('Temple', 'Temple'), ('Hospital', 'Hospital'), ('Stadium', 'Stadium')], max_length=50),
        ),
    ]
