# Generated by Django 6.0 on 2026-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_poi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.CharField(choices=[('University', 'University'), ('Hospital', 'Hospital'), ('Temple', 'Temple')], max_length=50),
        ),
    ]
